[package]
name = "vector-fields"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetra = "0.6"
num = "0.4.0"
rand = "0.8.4"
image = "0.23"
scoped_threadpool = "0.1.9"
